// If GPU with CUDA set to true
pub const IS_CUDA: bool = false;
// Config yolo file path
pub const CONFIG: &'static str = "assets/yolo-v3.cfg";
// Weights yolo file path
pub const WEIGHTS: &'static str = "assets/yolo-v3.ot";
// Confidence above which guess is taken to account
// Path to temporary file that is used for setting torch Tensor
pub const TEMPORARY_FILE_PATH: &'static str = "assets/temporary.jpg";
// Confidence threshold is the probability above which We decide to treat recognition as valid
pub const CONFIDENCE_THRESHOLD: f64 = 0.5;
// Names threshold is the probability above which We decide to treat recognition type as valid
pub const NMS_THRESHOLD: f64 = 0.4;
// Names are objects than Neuro Network knows and can recognize
pub const NAMES: [&'static str; 80] = [
    "person",
    "bicycle",
    "car",
    "motorbike",
    "aeroplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "sofa",
    "pottedplant",
    "bed",
    "diningtable",
    "toilet",
    "tvmonitor",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
];
